# Generated by Django 6.0.1 on 2026-01-10 16:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("artworks", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Artwork",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("creator", models.CharField(blank=True, max_length=255, null=True)),
                ("date", models.CharField(blank=True, max_length=50, null=True)),
                ("museum", models.CharField(blank=True, max_length=255, null=True)),
                ("movement", models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
