# Generated by Django 6.0.1 on 2026-01-11 12:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("artworks", "0002_artwork"),
    ]

    operations = [
        migrations.RenameField(
            model_name="dbpediaartist",
            old_name="created_at",
            new_name="fetched_at",
        ),
        migrations.AlterField(
            model_name="dbpediaartist",
            name="name",
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
    ]
