# Generated by Django 6.0.1 on 2026-01-12 20:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("artworks", "0003_rename_created_at_dbpediaartist_fetched_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="GettyAAT",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("term", models.CharField(db_index=True, max_length=255, unique=True)),
                ("aat_id", models.CharField(blank=True, max_length=50, null=True)),
                ("aat_url", models.URLField(blank=True, null=True)),
                ("preferred_label", models.CharField(blank=True, max_length=255, null=True)),
                ("fetched_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="GettyULAN",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=255, unique=True)),
                ("ulan_id", models.CharField(blank=True, max_length=50, null=True)),
                ("ulan_url", models.URLField(blank=True, null=True)),
                ("preferred_label", models.CharField(blank=True, max_length=255, null=True)),
                ("fetched_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
