# Generated by Django 6.0.1 on 2026-01-13 12:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("artworks", "0004_gettyaat_gettyulan"),
    ]

    operations = [
        migrations.AddField(
            model_name="artwork",
            name="image_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="dbpediaartist",
            name="image_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
